project: FL4ME
entity: louisewiljander-ludwig-maximilianuniversity-of-munich
program: run_sweep.py
method: random
metric:
  name: final_test_acc
  goal: maximize
parameters:
  clipping_norm:
    values: [0.5, 1.0, 2.0, 5.0]
  local_epochs:
    values: [1, 2, 3, 5, 6, 10]
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  noise_multiplier:
    distribution: uniform
    min: 0.1
    max: 1.0
  num_server_rounds:
    values: [3, 5, 6, 10, 15, 30]
  proximal_mu:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1